package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("category", "id", Category.class);
		arp.addMapping("collection", "id", Collection.class);
		arp.addMapping("reply", "id", Reply.class);
		arp.addMapping("test", "id", Test.class);
		arp.addMapping("topic", "id", Topic.class);
		arp.addMapping("user", "id", User.class);
	}
}

