package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTopic<M extends BaseTopic<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAdminId(java.lang.Integer adminId) {
		set("adminId", adminId);
		return (M)this;
	}
	
	public java.lang.Integer getAdminId() {
		return getInt("adminId");
	}

	public M setCategoryId(java.lang.Integer categoryId) {
		set("categoryId", categoryId);
		return (M)this;
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("categoryId");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setPubDate(java.util.Date pubDate) {
		set("pubDate", pubDate);
		return (M)this;
	}
	
	public java.util.Date getPubDate() {
		return get("pubDate");
	}

	public M setCoverPic(java.lang.String coverPic) {
		set("coverPic", coverPic);
		return (M)this;
	}
	
	public java.lang.String getCoverPic() {
		return getStr("coverPic");
	}

	public M setLink(java.lang.String link) {
		set("link", link);
		return (M)this;
	}
	
	public java.lang.String getLink() {
		return getStr("link");
	}

	public M setLinkName(java.lang.String linkName) {
		set("linkName", linkName);
		return (M)this;
	}
	
	public java.lang.String getLinkName() {
		return getStr("linkName");
	}

}
