package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCollection<M extends BaseCollection<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTopicId(java.lang.Integer topicId) {
		set("topicId", topicId);
		return (M)this;
	}
	
	public java.lang.Integer getTopicId() {
		return getInt("topicId");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setCollectionTime(java.util.Date collectionTime) {
		set("collectionTime", collectionTime);
		return (M)this;
	}
	
	public java.util.Date getCollectionTime() {
		return get("collectionTime");
	}

}
