package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAdminName(java.lang.String adminName) {
		set("adminName", adminName);
		return (M)this;
	}
	
	public java.lang.String getAdminName() {
		return getStr("adminName");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setNickName(java.lang.String nickName) {
		set("nickName", nickName);
		return (M)this;
	}
	
	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setSuper(java.lang.Integer _super) {
		set("super", _super);
		return (M)this;
	}
	
	public java.lang.Integer getSuper() {
		return getInt("super");
	}

}
